### ISSUE TITLE
[BUG] syntax error in build.sh

### ISSUE THREAD

**Issue by RogueScholar** [Silicasandwhich/Bibata_Cursor_Translucent#4]
**Describe the bug**
Running build.sh with Inkscape 1.1 produces a litany of syntax errors that read:
`Unknown option --without-gui`

The most recent revision of the man page reads:

```
-z, --without-gui
Do not open the GUI (on Unix, do not use X server); only process the files from console.  This is assumed for -p, -e, -l, and --vacuum-defs options. It cannot be used in
conjunction with the --verb option.
```

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04 LTS "Focal Fossa"
 - Browser Vivaldi-snapshot
 - Version 2.11.1811.28

**Additional context**
Naturally this is a nightly build of Inkscape running of a prerelease test of Kubuntu, but since this issue will manifest upon release, I thought you'd appreciate the heads up. Also, it'd be good to use a case statement in the script when you need elevated privileges to hunt for kdesu and pkexec in addition to gksu (and fallback to sudo failing those), since gksu is only present in GNOME Desktop Environments. That's where the script crapped out for me; the inkscape stuff was just diarrhea of the terminal buffer. :rofl: 

Nice choice to fork this and tinker with the alpha values. I look forward to test driving it.

Cheers,
RS

**Comment by silica-dev** [comment]
Good to know. I will investigate what's causing the issue. The install script is almost verbatim to the one in the original repo at the time I forked it, so ill see what the maintainer of the original repo did to fix it.

**Comment by bpoteryko** [comment]
I have this issue as well. I'd love a fix; it's absolutely my favourite cursor I've used!

**Comment by silica-dev** [comment]
hey, sorry it's been so long. thanks for the encouraging words! i'm currently working on a solution that should cut out the need for inkscape altogether. instead of having the end user build it locally, i am currently building it on my computer so that when you download it you only need to install. i'm also adding in a few if statements so that not having gksu won't cause an error. i'm currently waiting on the theme to build, so ill update the github and aur repo when it's done. thanks for bringing this to my attention!

**Comment by silica-dev** [comment]
Alright, I've updated the aur repo and made a [new release](https://github.com/Silicasandwhich/Bibata_Cursor_Translucent/releases/tag/v1.1). You can build it from source there. I'll be working on a debian release next.
